# Generated by Django 4.1.5 on 2023-02-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
