# Generated by Django 4.1.5 on 2023-02-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
