# Generated by Django 4.1.5 on 2023-02-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0005_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='barcode',
        ),
    ]
