# Generated by Django 4.1.5 on 2023-02-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0006_remove_cart_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='barcode',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
