# Generated by Django 4.1.5 on 2023-02-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0007_cart_barcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
