# Generated by Django 4.1.5 on 2023-02-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0008_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(blank=True, default='0', null=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('price', models.IntegerField(blank=True, default='0', null=True)),
                ('total_price', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
    ]
